In [4]:
# 游戏背包问题

In [5]:
# 封闭图形的面积

In [6]:
# 安全系数

In [7]:
# 完美对

In [90]:
nums = list(map(int, input().split()))
n = nums[0]
k = nums[1]
ans = []
import numpy as np
for i in range(n):
    res = list(map(int, input().split()))
    ans.append(res)
count = 0
ans = np.array(ans)
for i in range(n):
    for j in range(i+1, n):
        print(ans[i] + ans[j])
        if (ans[i] + ans[j] == np.sum(ans[i] + ans[j])/k).all():
            count += 1
print(count)

5 3
2 11 21
19 10 1
20 11 1
6 15 24
18 27 36
[21 21 22]
[22 22 22]
[ 8 26 45]
[20 38 57]
[39 21  2]
[25 25 25]
[37 37 37]
[26 26 25]
[38 38 37]
[24 42 60]
3


In [8]:
# 朋友圈

In [41]:
T = int(input())
for i in range(T):
    n = int(input())
    ans = []
    for _ in range(n):
        res = list(map(int, input().split()))
        ans.append(res)
    for m in range(len(ans)):
        for y in range(len(ans)):
            if ans[y][0] in ans[m] or ans[y][1] in ans[m]:
                ans[m] += ans[y]
                break
    pathh = []
    for t in ans:
        t = set(t)
        pathh.append(len(t))
    print(max(pathh))

1
4
1 2
3 4
5 6
1 6
3


In [42]:
ans

[[1, 2, 1, 2], [3, 4, 3, 4], [5, 6, 5, 6], [1, 6, 1, 2, 1, 2]]

In [3]:
set([1,2,3,1,2,1])

{1, 2, 3}

In [21]:
ans = [[1,2], [2, 3, 2]]

In [25]:
path = []
for i in ans:
    i = set(i)
    path.append(len(i))

In [46]:
import numpy as np

In [68]:
a = [1, 2]
b = [2, 3]
c = [2, 3]

In [69]:
a = np.array(a)
b = np.array(b)
c = np.array(c)

In [76]:
if (a + b == c + c).all():
    print(1)

In [61]:
d.all()

True

In [77]:
e = [[1,2], [3,4]]

In [78]:
e = np.array(e)

In [82]:
for i in range(len(e)):
    print(e[i])

[1 2]
[3 4]


In [83]:
np.sum(e)

10

In [84]:
a == 1

array([ True, False], dtype=bool)